apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service1-chart.fullname" . }}
  labels:
    {{- include "service1-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service1-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service1-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: krampert/service1:2.0
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP